version: '3.8'
services:
  proxy:
    container_name: traefik
    image: traefik:v2.2
    networks:
      - web_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    ports:
      - "80:80"
      - "8090:8080"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
      - --api.insecure=true
    labels:
      - traefik.docker.network=web_network
      - traefik.http.routers.${STACK_NAME?Variable not set}-web_network-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.services.${STACK_NAME?Variable not set}-web_network.loadbalancer.server.port=80

  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    env_file:
      - .env
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p $MONGODB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - db_network

  core:
    image: julenbadiola/tfmcore:master
    container_name: core
    restart: always
    env_file: .env
    build: .
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - .:/app
    networks:
      - db_network
      - web_network
    ports:
      - "5005:5005"
    command: python manage.py runserver 0.0.0.0:5005
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_network
      - traefik.http.services.tfm-googledrive.loadbalancer.server.port=5005
      - traefik.http.routers.tfm-googledrive.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)
  
  # nginx:
  #   container_name: nginx
  #   restart: always
  #   image: "nginx:latest"
  #   ports:
  #     - "85:85"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   networks:
  #     - web_network
  #   depends_on: 
  #     - appseed-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 