# Generated by Django 3.2.11 on 2022-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'product'), ('transaction', 'transaction')], max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('value', models.IntegerField()),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
