name: build-and-publish-docker

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - '*'
    paths:
      - ./app/**
      - ./services/**
      - ./test_services/**
      - Dockerfile
      - "*.yml"
      - Makefile
      - .github/workflows/build-and-publish-docker.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers needed for testing and run tests
        run: |
          make testing
          make test-coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish coverage to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          base-path: app
          path-to-lcov: app/coverage.lcov

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Sets env vars for master
        run: |
          echo "DOCKER_IMAGE_NAME=badiolajulen/plugger:latest" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/master'
      
      - name: Sets env vars for others
        run: |
          echo "DOCKER_IMAGE_NAME=badiolajulen/plugger:${{ github.ref_name }}" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/master'

      - name: Build and push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            badiolajulen/plugger:${{env.DOCKER_IMAGE_NAME}}
            badiolajulen/plugger:${{env.DOCKER_IMAGE_NAME}}.$(date +'%Y%m%d')
          cache-from: type=registry,ref=badiolajulen/plugger:buildcache
          cache-to: type=registry,ref=badiolajulen/plugger:buildcache,mode=max